'use client'

import React from 'react'
import { motion } from 'framer-motion'

type HeroGridProps = {
  tileSize?: number
  stroke?: string
  fill?: string
  className?: string
  width?: string
  height?: string
}

const AnimatedHeroGrid = ({
  tileSize = 39,
  stroke = '#8A8A8A',
  fill = 'none',
  width = '100%',
  height = 'auto',
  className = ''
}: HeroGridProps) => {
  const squareVariants = {
    hidden: { opacity: 0 },
    visible: (distance: number) => ({
      opacity: 1,
      transition: {
        delay: distance * 0.35, // im dalej, tym większe opóźnienie
        duration: 0.5,
        ease: 'easeOut'
      }
    })
  }

  const center = { x: 585.5 + 39 / 2, y: 273.5 + 39 / 2 } // środek kwadratu sq16-r8

  const getDistance = (x: number, y: number) => {
    const dx = x + 39 / 2 - center.x
    const dy = y + 39 / 2 - center.y
    return Math.sqrt(dx * dx + dy * dy) / 100 // dzielimy na 100, żeby wartości były mniejsze
  }

  return (
    <svg
      width={width}
      height={height}
      viewBox='0 0 1171 547'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      className={className}
    >
      <g id='HERO GRID FINAL'>
        <g id='row01'>
          <motion.path
            id='sq01-r1'
            d='M907 0.5H936.5V39.5H897.5V10C897.5 4.7533 901.753 0.5 907 0.5Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(907, 0.5)}
          />
          <motion.rect
            id='sq02-r1'
            x='936.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 0.5)}
          />
          <motion.rect
            id='sq03-r1'
            x='975.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 0.5)}
          />
          <motion.rect
            id='sq04-r1'
            x='1014.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 0.5)}
          />
        </g>
        <g id='row02'>
          <motion.path
            id='sq01-r2'
            d='M556 39.5H585.5V78.5H546.5V49C546.5 43.7533 550.753 39.5 556 39.5Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(556, 39)}
          />
          <motion.rect
            id='sq02-r2'
            x='585.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 39.5)}
          />
          <motion.rect
            id='sq03-r2'
            x='624.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 39.5)}
          />
          <motion.rect
            id='sq04-r2'
            x='780.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 39.5)}
          />
          <motion.rect
            id='sq05-r2'
            x='819.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 39.5)}
          />
          <motion.rect
            id='sq06-r2'
            x='858.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 39.5)}
          />
          <motion.rect
            id='sq07-r2'
            x='897.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 39.5)}
          />
          <motion.rect
            id='sq08-r2'
            x='936.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 39.5)}
          />
          <motion.rect
            id='sq09-r2'
            x='975.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 39.5)}
          />
          <motion.rect
            id='sq10-r2'
            x='1014.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 39.5)}
          />
          <motion.rect
            id='sq11-r2'
            x='1053.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 39.5)}
          />
          <motion.rect
            id='sq12-r2'
            x='1092.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1092.5, 39.5)}
          />
        </g>
        <g id='row03'>
          <motion.rect
            id='sq01-r3'
            x='546.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 78.5)}
          />
          <motion.rect
            id='sq02-r3'
            x='585.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 78.5)}
          />
          <motion.rect
            id='sq03-r3'
            x='624.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 78.5)}
          />
          <motion.rect
            id='sq04-r3'
            x='780.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 78.5)}
          />
          <motion.rect
            id='sq05-r3'
            x='819.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 78.5)}
          />
          <motion.rect
            id='sq06-r3'
            x='858.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 78.5)}
          />
          <motion.rect
            id='sq07-r3'
            x='897.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 78.5)}
          />
          <motion.rect
            id='sq08-r3'
            x='936.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 78.5)}
          />
          <motion.rect
            id='sq09-r3'
            x='975.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 78.5)}
          />
          <motion.rect
            id='sq10-r3'
            x='1014.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 78.5)}
          />
          <motion.rect
            id='sq11-r3'
            x='1053.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 78.5)}
          />
          <motion.rect
            id='sq12-r3'
            x='1092.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1092.5, 78.5)}
          />
          <motion.path
            id='sq13-r3'
            d='M1161 78.5C1166.25 78.5 1170.5 82.7533 1170.5 88V117.5H1131.5V78.5H1161Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1161, 78.5)}
          />
        </g>
        <g id='row04'>
          <motion.rect
            id='sq01-r4'
            x='507.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 117.5)}
          />
          <motion.rect
            id='sq02-r4'
            x='546.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 117.5)}
          />
          <motion.rect
            id='sq03-r4'
            x='585.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 117.5)}
          />
          <motion.rect
            id='sq04-r4'
            x='624.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 117.5)}
          />
          <motion.rect
            id='sq05-r4'
            x='663.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 117.5)}
          />
          <motion.rect
            id='sq06-r4'
            x='702.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 117.5)}
          />
          <motion.rect
            id='sq07-r4'
            x='741.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 117.5)}
          />
          <motion.rect
            id='sq08-r4'
            x='780.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 117.5)}
          />
          <motion.rect
            id='sq09-r4'
            x='819.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 117.5)}
          />
          <motion.rect
            id='sq10-r4'
            x='858.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 117.5)}
          />
          <motion.rect
            id='sq11-r4'
            x='897.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 117.5)}
          />
          <motion.rect
            id='sq12-r4'
            x='936.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 117.5)}
          />
          <motion.rect
            id='sq13-r4'
            x='975.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 117.5)}
          />
          <motion.rect
            id='sq14-r4'
            x='1014.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 117.5)}
          />
          <motion.rect
            id='sq15-r4'
            x='1053.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 117.5)}
          />
          <motion.rect
            id='sq16-r4'
            x='1092.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1092.5, 117.5)}
          />
          <motion.rect
            id='sq17-r4'
            x='1131.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1131.5, 117.5)}
          />
        </g>
        <g id='row05'>
          <motion.rect
            id='sq01-r5'
            x='507.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 156.5)}
          />
          <motion.rect
            id='sq02-r5'
            x='546.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 156.5)}
          />
          <motion.rect
            id='sq03-r5'
            x='585.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 156.5)}
          />
          <motion.rect
            id='sq04-r5'
            x='624.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 156.5)}
          />
          <motion.rect
            id='sq05-r5'
            x='663.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 156.5)}
          />
          <motion.rect
            id='sq06-r5'
            x='702.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 156.5)}
          />
          <motion.rect
            id='sq07-r5'
            x='741.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 156.5)}
          />
          <motion.rect
            id='sq08-r5'
            x='780.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 156.5)}
          />
          <motion.rect
            id='sq09-r5'
            x='819.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 156.5)}
          />
          <motion.rect
            id='sq10-r5'
            x='858.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 156.5)}
          />
          <motion.rect
            id='sq11-r5'
            x='897.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 156.5)}
          />
          <motion.rect
            id='sq12-r5'
            x='936.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 156.5)}
          />
          <motion.rect
            id='sq13-r5'
            x='975.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 156.5)}
          />
          <motion.rect
            id='sq14-r5'
            x='1014.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 156.5)}
          />
          <motion.rect
            id='sq15-r5'
            x='1053.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 156.5)}
          />
          <motion.rect
            id='sq16-r5'
            x='1092.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1092.5, 156.5)}
          />
          <motion.rect
            id='sq17-r5'
            x='1131.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1131.5, 156.5)}
          />
        </g>
        <g id='row06'>
          <motion.rect
            id='sq01-r6'
            x='507.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 195.5)}
          />
          <motion.rect
            id='sq02-r6'
            x='546.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 195.5)}
          />
          <motion.rect
            id='sq03-r6'
            x='585.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 195.5)}
          />
          <motion.rect
            id='sq04-r6'
            x='624.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 195.5)}
          />
          <motion.rect
            id='sq05-r6'
            x='663.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 195.5)}
          />
          <motion.rect
            id='sq06-r6'
            x='702.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 195.5)}
          />
          <motion.rect
            id='sq07-r6'
            x='741.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 195.5)}
          />
          <motion.rect
            id='sq08-r6'
            x='780.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 195.5)}
          />
          <motion.rect
            id='sq09-r6'
            x='819.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 195.5)}
          />
          <motion.rect
            id='sq10-r6'
            x='858.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 195.5)}
          />
          <motion.rect
            id='sq11-r6'
            x='897.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 195.5)}
          />
          <motion.rect
            id='sq12-r6'
            x='936.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 195.5)}
          />
          <motion.rect
            id='sq13-r6'
            x='975.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 195.5)}
          />
          <motion.rect
            id='sq14-r6'
            x='1014.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 195.5)}
          />
          <motion.rect
            id='sq15-r6'
            x='1053.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 195.5)}
          />
          <motion.rect
            id='sq16-r6'
            x='1092.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1092.5, 195.5)}
          />
          <motion.rect
            id='sq17-r6'
            x='1131.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1131.5, 195.5)}
          />
        </g>
        <g id='row07'>
          <motion.path
            id='sq01-r7'
            d='M205 234.5H234.5V273.5H195.5V244C195.5 238.753 199.753 234.5 205 234.5Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(205, 234.5)}
          />
          <motion.rect
            id='sq02-r7'
            x='234.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 234.5)}
          />
          <motion.rect
            id='sq03-r7'
            x='273.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 234.5)}
          />
          <motion.rect
            id='sq04-r7'
            x='312.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 234.5)}
          />
          <motion.rect
            id='sq05-r7'
            x='351.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 234.5)}
          />
          <motion.rect
            id='sq06-r7'
            x='390.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 234.5)}
          />
          <motion.rect
            id='sq07-r7'
            x='429.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 234.5)}
          />
          <motion.rect
            id='sq08-r7'
            x='468.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 234.5)}
          />
          <motion.rect
            id='sq09-r7'
            x='507.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 234.5)}
          />
          <motion.rect
            id='sq10-r7'
            x='546.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 234.5)}
          />
          <motion.rect
            id='sq11-r7'
            x='585.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 234.5)}
          />
          <motion.rect
            id='sq12-r7'
            x='624.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 234.5)}
          />
          <motion.rect
            id='sq13-r7'
            x='663.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 234.5)}
          />
          <motion.rect
            id='sq14-r7'
            x='702.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 234.5)}
          />
          <motion.rect
            id='sq15-r7'
            x='741.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 234.5)}
          />
          <motion.rect
            id='sq16-r7'
            x='780.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 234.5)}
          />
          <motion.rect
            id='sq17-r7'
            x='819.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 234.5)}
          />
          <motion.rect
            id='sq18-r7'
            x='858.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 234.5)}
          />
          <motion.rect
            id='sq19-r7'
            x='897.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 234.5)}
          />
          <motion.rect
            id='sq20-r7'
            x='936.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 234.5)}
          />
          <motion.rect
            id='sq21-r7'
            x='975.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 234.5)}
          />
          <motion.rect
            id='sq22-r7'
            x='1014.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 234.5)}
          />
          <motion.rect
            id='sq23-r7'
            x='1053.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 234.5)}
          />
        </g>
        <g id='row08'>
          <motion.rect
            id='sq01-r8'
            x='0.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(0.5, 273.5)}
          />
          <motion.rect
            id='sq02-r8'
            x='39.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(39.5, 273.5)}
          />
          <motion.rect
            id='sq03-r8'
            x='78.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(78.5, 273.5)}
          />
          <motion.rect
            id='sq04-r8'
            x='117.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 273.5)}
          />
          <motion.rect
            id='sq05-r8'
            x='156.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 273.5)}
          />
          <motion.rect
            id='sq06-r8'
            x='195.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 273.5)}
          />
          <motion.rect
            id='sq07-r8'
            x='234.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 273.5)}
          />
          <motion.rect
            id='sq08-r8'
            x='273.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 273.5)}
          />
          <motion.rect
            id='sq09-r8'
            x='312.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 273.5)}
          />
          <motion.rect
            id='sq10-r8'
            x='351.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 273.5)}
          />
          <motion.rect
            id='sq11-r8'
            x='390.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 273.5)}
          />
          <motion.rect
            id='sq12-r8'
            x='429.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 273.5)}
          />
          <motion.rect
            id='sq13-r8'
            x='468.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 273.5)}
          />
          <motion.rect
            id='sq14-r8'
            x='507.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 273.5)}
          />
          <motion.rect
            id='sq15-r8'
            x='546.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 273.5)}
          />
          <motion.rect
            id='sq16-r8'
            x='585.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 273.5)}
          />
          <motion.rect
            id='sq17-r8'
            x='624.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 273.5)}
          />
          <motion.rect
            id='sq18-r8'
            x='663.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 273.5)}
          />
          <motion.rect
            id='sq19-r8'
            x='702.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 273.5)}
          />
          <motion.rect
            id='sq20-r8'
            x='741.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 273.5)}
          />
          <motion.rect
            id='sq21-r8'
            x='780.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 273.5)}
          />
          <motion.rect
            id='sq22-r8'
            x='819.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 273.5)}
          />
          <motion.rect
            id='sq23-r8'
            x='858.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 273.5)}
          />
          <motion.rect
            id='sq24-r8'
            x='897.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 273.5)}
          />
          <motion.rect
            id='sq25-r8'
            x='936.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(936.5, 273.5)}
          />
          <motion.rect
            id='sq26-r8'
            x='975.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(975.5, 273.5)}
          />
          <motion.rect
            id='sq27-r8'
            x='1014.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1014.5, 273.5)}
          />
          <motion.rect
            id='sq28-r8'
            x='1053.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(1053.5, 273.5)}
          />
        </g>
        <g id='row09'>
          <motion.rect
            id='sq01-r9'
            x='0.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(0.5, 312.5)}
          />
          <motion.rect
            id='sq02-r9'
            x='39.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(39.5, 312.5)}
          />
          <motion.rect
            id='sq03-r9'
            x='78.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(78.5, 312.5)}
          />
          <motion.rect
            id='sq04-r9'
            x='117.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 312.5)}
          />
          <motion.rect
            id='sq05-r9'
            x='156.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 312.5)}
          />
          <motion.rect
            id='sq06-r9'
            x='195.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 312.5)}
          />
          <motion.rect
            id='sq07-r9'
            x='234.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 312.5)}
          />
          <motion.rect
            id='sq08-r9'
            x='273.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 312.5)}
          />
          <motion.rect
            id='sq09-r9'
            x='312.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 312.5)}
          />
          <motion.rect
            id='sq10-r9'
            x='351.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 312.5)}
          />
          <motion.rect
            id='sq11-r9'
            x='390.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 312.5)}
          />
          <motion.rect
            id='sq12-r9'
            x='429.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 312.5)}
          />
          <motion.rect
            id='sq13-r9'
            x='468.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 312.5)}
          />
          <motion.rect
            id='sq14-r9'
            x='507.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 312.5)}
          />
          <motion.rect
            id='sq15-r9'
            x='546.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 312.5)}
          />
          <motion.rect
            id='sq16-r9'
            x='585.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 312.5)}
          />
          <motion.rect
            id='sq17-r9'
            x='624.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 312.5)}
          />
          <motion.rect
            id='sq18-r9'
            x='663.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 312.5)}
          />
          <motion.rect
            id='sq19-r9'
            x='702.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 312.5)}
          />
          <motion.rect
            id='sq20-r9'
            x='741.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(741.5, 312.5)}
          />
          <motion.rect
            id='sq21-r9'
            x='780.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(780.5, 312.5)}
          />
          <motion.rect
            id='sq22-r9'
            x='819.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(819.5, 312.5)}
          />
          <motion.rect
            id='sq23-r9'
            x='858.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(858.5, 312.5)}
          />
          <motion.rect
            id='sq24-r9'
            x='897.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(897.5, 312.5)}
          />
        </g>
        <g id='row10'>
          <motion.rect
            id='sq01-r10'
            x='0.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(0.5, 351.5)}
          />
          <motion.rect
            id='sq02-r10'
            x='39.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(39.5, 351.5)}
          />
          <motion.rect
            id='sq03-r10'
            x='78.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(78.5, 351.5)}
          />
          <motion.rect
            id='sq04-r10'
            x='117.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 351.5)}
          />
          <motion.rect
            id='sq05-r10'
            x='156.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 351.5)}
          />
          <motion.rect
            id='sq06-r10'
            x='195.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 351.5)}
          />
          <motion.rect
            id='sq07-r10'
            x='234.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 351.5)}
          />
          <motion.rect
            id='sq08-r10'
            x='273.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 351.5)}
          />
          <motion.rect
            id='sq09-r10'
            x='312.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 351.5)}
          />
          <motion.rect
            id='sq10-r10'
            x='351.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 351.5)}
          />
          <motion.rect
            id='sq11-r10'
            x='390.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 351.5)}
          />
          <motion.rect
            id='sq12-r10'
            x='429.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 351.5)}
          />
          <motion.rect
            id='sq13-r10'
            x='468.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 351.5)}
          />
          <motion.rect
            id='sq14-r10'
            x='507.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 351.5)}
          />
          <motion.rect
            id='sq15-r10'
            x='546.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 351.5)}
          />
          <motion.rect
            id='sq16-r10'
            x='585.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 351.5)}
          />
          <motion.rect
            id='sq17-r10'
            x='624.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 351.5)}
          />
          <motion.rect
            id='sq18-r10'
            x='663.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 351.5)}
          />
          <motion.rect
            id='sq19-r10'
            x='702.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(702.5, 351.5)}
          />
        </g>
        <g id='row11'>
          <motion.path
            id='sq01-r11'
            d='M39.5 390.5V429.5H10C4.7533 429.5 0.5 425.247 0.5 420V390.5H39.5Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(39.5, 390.5)}
          />
          <motion.rect
            id='sq02-r11'
            x='39.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(39.5, 390.5)}
          />
          <motion.rect
            id='sq03-r11'
            x='78.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(78.5, 390.5)}
          />
          <motion.rect
            id='sq04-r11'
            x='117.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 390.5)}
          />
          <motion.rect
            id='sq05-r11'
            x='156.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 390.5)}
          />
          <motion.rect
            id='sq06-r11'
            x='195.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 390.5)}
          />
          <motion.rect
            id='sq07-r11'
            x='234.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 390.5)}
          />
          <motion.rect
            id='sq08-r11'
            x='273.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 390.5)}
          />
          <motion.rect
            id='sq09-r11'
            x='312.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 390.5)}
          />
          <motion.rect
            id='sq10-r11'
            x='351.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 390.5)}
          />
          <motion.rect
            id='sq11-r11'
            x='390.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 390.5)}
          />
          <motion.rect
            id='sq12-r11'
            x='429.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 390.5)}
          />
          <motion.rect
            id='sq13-r11'
            x='468.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 390.5)}
          />
          <motion.rect
            id='sq14-r11'
            x='507.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 390.5)}
          />
          <motion.rect
            id='sq15-r11'
            x='546.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 390.5)}
          />
          <motion.rect
            id='sq16-r11'
            x='585.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 390.5)}
          />
          <motion.rect
            id='sq17-r11'
            x='624.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 390.5)}
          />
          <motion.rect
            id='sq18-r11'
            x='663.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(663.5, 390.5)}
          />
        </g>
        <g id='row12'>
          <motion.rect
            id='sq01-r12'
            x='117.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 429.5)}
          />
          <motion.rect
            id='sq02-r12'
            x='156.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 429.5)}
          />
          <motion.rect
            id='sq03-r12'
            x='195.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 429.5)}
          />
          <motion.rect
            id='sq04-r12'
            x='234.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 429.5)}
          />
          <motion.rect
            id='sq05-r12'
            x='273.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 429.5)}
          />
          <motion.rect
            id='sq06-r12'
            x='312.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 429.5)}
          />
          <motion.rect
            id='sq07-r12'
            x='351.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 429.5)}
          />
          <motion.rect
            id='sq08-r12'
            x='390.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 429.5)}
          />
          <motion.rect
            id='sq09-r12'
            x='429.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 429.5)}
          />
          <motion.rect
            id='sq10-r12'
            x='468.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 429.5)}
          />
          <motion.rect
            id='sq11-r12'
            x='507.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 429.5)}
          />
          <motion.rect
            id='sq12-r12'
            x='546.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 429.5)}
          />
          <motion.rect
            id='sq13-r12'
            x='585.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(585.5, 429.5)}
          />
          <motion.rect
            id='sq14-r12'
            x='624.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(624.5, 429.5)}
          />
          <motion.path
            id='sq15-r12'
            d='M702.5 429.5V459C702.5 464.247 698.247 468.5 693 468.5H663.5V429.5H702.5Z'
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(907, 0.5)}
          />
        </g>
        <g id='row13'>
          <motion.rect
            id='sq01-r13'
            x='117.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 468.5)}
          />
          <motion.rect
            id='sq02-r13'
            x='156.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 468.5)}
          />
          <motion.rect
            id='sq03-r13'
            x='195.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 468.5)}
          />
          <motion.rect
            id='sq04-r13'
            x='234.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 468.5)}
          />
          <motion.rect
            id='sq05-r13'
            x='273.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 468.5)}
          />
          <motion.rect
            id='sq06-r13'
            x='312.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 468.5)}
          />
          <motion.rect
            id='sq07-r13'
            x='351.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 468.5)}
          />
          <motion.rect
            id='sq08-r13'
            x='390.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 468.5)}
          />
          <motion.rect
            id='sq09-r13'
            x='429.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 468.5)}
          />
          <motion.rect
            id='sq10-r13'
            x='468.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(468.5, 468.5)}
          />
          <motion.rect
            id='sq11-r13'
            x='507.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(507.5, 468.5)}
          />
          <motion.rect
            id='sq12-r13'
            x='546.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(546.5, 468.5)}
          />
        </g>
        <g id='row14'>
          <motion.rect
            id='sq01-r14'
            x='117.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(117.5, 507.5)}
          />
          <motion.rect
            id='sq02-r14'
            x='156.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(156.5, 507.5)}
          />
          <motion.rect
            id='sq03-r14'
            x='195.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(195.5, 507.5)}
          />
          <motion.rect
            id='sq04-r14'
            x='234.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(234.5, 507.5)}
          />
          <motion.rect
            id='sq05-r14'
            x='273.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(273.5, 507.5)}
          />
          <motion.rect
            id='sq06-r14'
            x='312.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(312.5, 507.5)}
          />
          <motion.rect
            id='sq07-r14'
            x='351.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(351.5, 507.5)}
          />
          <motion.rect
            id='sq08-r14'
            x='390.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(390.5, 507.5)}
          />
          <motion.rect
            id='sq09-r14'
            x='429.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
            variants={squareVariants}
            initial='hidden'
            animate='visible'
            custom={getDistance(429.5, 507.5)}
          />
        </g>
      </g>
    </svg>
  )
}

export default AnimatedHeroGrid
