import React, { useState } from 'react'
import { animate, hover, motion, useScroll, useTransform } from 'framer-motion'

type HeroGridProps = {
  tileSize?: number
  stroke?: string
  fill?: string
  className?: string
  width?: string
  height?: string
}

const HeroGrid = ({
  tileSize = 39,
  stroke = '#8A8A8A',
  fill = 'none',
  width = '100%',
  height = 'auto',
  className = 'absolute z-[-2]'
}: HeroGridProps) => {
  const { scrollYProgress } = useScroll()

  const rotateElement08 = useTransform(
    scrollYProgress,
    [0, 1],
    ['0deg', '960deg']
  )

  return (
    <svg
      width={width}
      height={height}
      viewBox='0 0 1171 547'
      fill='none'
      xmlns='http://www.w3.org/2000/svg'
      className={className}
    >
      <g id='hero-grid'>
        <g id='row01'>
          <motion.path
            id='sq01-r1'
            d='M907 0.5H936.5V39.5H897.5V10C897.5 4.7533 901.753 0.5 907 0.5Z'
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r1'
            x='936.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r1'
            x='975.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r1'
            x='1014.5'
            y='0.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row02'>
          <motion.path
            id='sq01-r2'
            d='M556 39.5H585.5V78.5H546.5V49C546.5 43.7533 550.753 39.5 556 39.5Z'
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r2'
            x='585.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r2'
            x='624.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r2'
            x='780.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r2'
            x='819.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r2'
            x='858.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r2'
            x='897.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r2'
            x='936.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r2'
            x='975.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r2'
            x='1014.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r2'
            x='1053.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r2'
            x='1092.5'
            y='39.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row03'>
          <motion.rect
            id='sq01-r3'
            x='546.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r3'
            x='585.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r3'
            x='624.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r3'
            x='780.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r3'
            x='819.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r3'
            x='858.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r3'
            x='897.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r3'
            x='936.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r3'
            x='975.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r3'
            x='1014.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r3'
            x='1053.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r3'
            x='1092.5'
            y='78.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.path
            id='sq13-r3'
            d='M1161 78.5C1166.25 78.5 1170.5 82.7533 1170.5 88V117.5H1131.5V78.5H1161Z'
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row04'>
          <motion.rect
            id='sq01-r4'
            x='507.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r4'
            x='546.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r4'
            x='585.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r4'
            x='624.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r4'
            x='663.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r4'
            x='702.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r4'
            x='741.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r4'
            x='780.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r4'
            x='819.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r4'
            x='858.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r4'
            x='897.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r4'
            x='936.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r4'
            x='975.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r4'
            x='1014.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r4'
            x='1053.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r4'
            x='1092.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r4'
            x='1131.5'
            y='117.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row05'>
          <motion.rect
            id='sq01-r5'
            x='507.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r5'
            x='546.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r5'
            x='585.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r5'
            x='624.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r5'
            x='663.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r5'
            x='702.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r5'
            x='741.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r5'
            x='780.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r5'
            x='819.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r5'
            x='858.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r5'
            x='897.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r5'
            x='936.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r5'
            x='975.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r5'
            x='1014.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r5'
            x='1053.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r5'
            x='1092.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r5'
            x='1131.5'
            y='156.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row06'>
          <motion.rect
            id='sq01-r6'
            x='507.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r6'
            x='546.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r6'
            x='585.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r6'
            x='624.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r6'
            x='663.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r6'
            x='702.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r6'
            x='741.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r6'
            x='780.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r6'
            x='819.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r6'
            x='858.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r6'
            x='897.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r6'
            x='936.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r6'
            x='975.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r6'
            x='1014.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r6'
            x='1053.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r6'
            x='1092.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r6'
            x='1131.5'
            y='195.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row07'>
          <motion.path
            id='sq01-r7'
            d='M205 234.5H234.5V273.5H195.5V244C195.5 238.753 199.753 234.5 205 234.5Z'
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r7'
            x='234.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r7'
            x='273.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r7'
            x='312.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r7'
            x='351.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r7'
            x='390.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r7'
            x='429.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r7'
            x='468.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r7'
            x='507.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r7'
            x='546.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r7'
            x='585.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r7'
            x='624.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r7'
            x='663.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r7'
            x='702.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r7'
            x='741.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r7'
            x='780.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r7'
            x='819.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq18-r7'
            x='858.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq19-r7'
            x='897.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq20-r7'
            x='936.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq21-r7'
            x='975.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq22-r7'
            x='1014.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq23-r7'
            x='1053.5'
            y='234.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row08'>
          <motion.rect
            id='sq01-r8'
            x='0.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r8'
            x='39.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r8'
            x='78.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r8'
            x='117.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r8'
            x='156.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r8'
            x='195.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r8'
            x='234.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r8'
            x='273.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r8'
            x='312.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r8'
            x='351.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r8'
            x='390.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r8'
            x='429.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r8'
            x='468.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r8'
            x='507.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r8'
            x='546.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r8'
            x='585.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r8'
            x='624.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq18-r8'
            x='663.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq19-r8'
            x='702.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq20-r8'
            x='741.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq21-r8'
            x='780.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq22-r8'
            x='819.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq23-r8'
            x='858.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq24-r8'
            x='897.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq25-r8'
            x='936.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq26-r8'
            x='975.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq27-r8'
            x='1014.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq28-r8'
            x='1053.5'
            y='273.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row09'>
          <motion.rect
            id='sq01-r9'
            x='0.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r9'
            x='39.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r9'
            x='78.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r9'
            x='117.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r9'
            x='156.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r9'
            x='195.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r9'
            x='234.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r9'
            x='273.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r9'
            x='312.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r9'
            x='351.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r9'
            x='390.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r9'
            x='429.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r9'
            x='468.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r9'
            x='507.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r9'
            x='546.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r9'
            x='585.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r9'
            x='624.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq18-r9'
            x='663.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq19-r9'
            x='702.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq20-r9'
            x='741.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq21-r9'
            x='780.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq22-r9'
            x='819.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq23-r9'
            x='858.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq24-r9'
            x='897.5'
            y='312.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row10'>
          <motion.rect
            id='sq01-r10'
            x='0.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r10'
            x='39.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r10'
            x='78.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r10'
            x='117.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r10'
            x='156.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r10'
            x='195.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r10'
            x='234.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r10'
            x='273.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r10'
            x='312.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r10'
            x='351.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r10'
            x='390.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r10'
            x='429.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r10'
            x='468.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r10'
            x='507.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r10'
            x='546.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r10'
            x='585.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r10'
            x='624.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq18-r10'
            x='663.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq19-r10'
            x='702.5'
            y='351.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row11'>
          <motion.path
            id='sq01-r11'
            d='M39.5 390.5V429.5H10C4.7533 429.5 0.5 425.247 0.5 420V390.5H39.5Z'
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r11'
            x='39.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r11'
            x='78.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r11'
            x='117.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r11'
            x='156.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r11'
            x='195.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r11'
            x='234.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r11'
            x='273.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r11'
            x='312.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r11'
            x='351.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r11'
            x='390.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r11'
            x='429.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r11'
            x='468.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r11'
            x='507.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq15-r11'
            x='546.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq16-r11'
            x='585.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq17-r11'
            x='624.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq18-r11'
            x='663.5'
            y='390.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row12'>
          <motion.rect
            id='sq01-r12'
            x='117.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r12'
            x='156.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r12'
            x='195.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r12'
            x='234.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r12'
            x='273.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r12'
            x='312.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r12'
            x='351.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r12'
            x='390.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r12'
            x='429.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r12'
            x='468.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r12'
            x='507.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r12'
            x='546.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq13-r12'
            x='585.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq14-r12'
            x='624.5'
            y='429.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.path
            id='sq15-r12'
            d='M702.5 429.5V459C702.5 464.247 698.247 468.5 693 468.5H663.5V429.5H702.5Z'
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row13'>
          <motion.rect
            id='sq01-r13'
            x='117.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r13'
            x='156.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r13'
            x='195.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r13'
            x='234.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r13'
            x='273.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r13'
            x='312.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r13'
            x='351.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r13'
            x='390.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r13'
            x='429.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq10-r13'
            x='468.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq11-r13'
            x='507.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq12-r13'
            x='546.5'
            y='468.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
        <g id='row14'>
          <motion.rect
            id='sq01-r14'
            x='117.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq02-r14'
            x='156.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq03-r14'
            x='195.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq04-r14'
            x='234.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq05-r14'
            x='273.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq06-r14'
            x='312.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq07-r14'
            x='351.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq08-r14'
            x='390.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
          <motion.rect
            id='sq09-r14'
            x='429.5'
            y='507.5'
            width={tileSize}
            height={tileSize}
            stroke={stroke}
            fill={fill}
          />
        </g>
      </g>
      <motion.g id='grid-elements'>
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.9 }}
          style={{ rotate: rotateElement08 }}
          id='element-08'
          d='M1043 29.5001L1037.47 19.9908L1020.03 29.9873V10H1008.97V29.9907L991.531 19.9943L986 29.5047L1003.44 39.4988L986.005 49.492L991.536 59.0012L1008.97 49.0048V69H1020.03V49.0117L1037.46 59.0058L1043 49.4954L1025.56 39.4988L1043 29.5001Z'
          fill='#303030'
        />
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.7 }}
          id='element-07'
          d='M936.5 255C936.459 243.692 927.297 234.538 916 234.538C927.322 234.538 936.5 225.343 936.5 214C936.541 225.308 945.703 234.462 957 234.462C945.678 234.462 936.5 243.657 936.5 255Z'
          fill='#8A8A8A'
        />
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
          id='element-06'
          d='M820 79H793.334V65.6674H806.667V52.3337H820V79ZM806.667 52.3337H793.334V65.6674H780V39H806.667V52.3337Z'
          fill='#8A8A8A'
        />
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          id='element-05'
          d='M624.508 140.538C626.279 148.466 632.515 154.703 640.435 156.462C632.49 158.226 626.239 164.498 624.491 172.461C622.72 164.534 616.484 158.296 608.564 156.537C616.51 154.773 622.76 148.502 624.508 140.538Z'
          fill='#C4C2BB'
          stroke='#8A8A8A'
        />
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          id='element-04'
          d='M585.5 333C585.459 321.692 576.297 312.538 565 312.538C576.322 312.538 585.5 303.343 585.5 292C585.541 303.308 594.703 312.462 606 312.462C594.678 312.462 585.5 321.657 585.5 333Z'
          fill='#8A8A8A'
        />
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          id='element-03'
          d='M546.511 318.269C549.244 335.289 562.677 348.721 579.679 351.426C562.628 354.138 549.169 367.641 546.488 384.73C543.754 367.71 530.322 354.277 513.32 351.573C530.371 348.862 543.831 335.358 546.511 318.269Z'
          fill='#C4C2BB'
          stroke='#8A8A8A'
        />
        <motion.g
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          id='element-02'
        >
          <path d='M215 507H205.5V497.5H215V507Z' fill='#8A8A8A' />
          <path d='M234 507H224.5V497.5H234V507Z' fill='#8A8A8A' />
          <path d='M205.5 497.5H196V488H205.5V497.5Z' fill='#8A8A8A' />
          <path d='M224.5 497.5H215V488H224.5V497.5Z' fill='#8A8A8A' />
          <path d='M215 488H205.5V478.5H215V488Z' fill='#8A8A8A' />
          <path d='M234 488H224.5V478.5H234V488Z' fill='#8A8A8A' />
          <path d='M205.5 478.5H196V469H205.5V478.5Z' fill='#8A8A8A' />
          <path d='M224.5 478.5H215V469H224.5V478.5Z' fill='#8A8A8A' />
        </motion.g>
        <motion.path
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          id='element-01'
          d='M78.0312 294.708C78.1823 294.3 78.7328 294.275 78.9336 294.632L78.9688 294.708L83.4082 306.705C83.5601 307.116 83.8843 307.44 84.2949 307.592L96.292 312.031C96.7001 312.182 96.7255 312.733 96.3682 312.934L96.292 312.969L84.2949 317.408C83.8843 317.56 83.5601 317.884 83.4082 318.295L78.9688 330.292C78.8177 330.7 78.2672 330.725 78.0664 330.368L78.0312 330.292L73.5918 318.295C73.4399 317.884 73.1157 317.56 72.7051 317.408L60.708 312.969C60.2999 312.818 60.2745 312.267 60.6318 312.066L60.708 312.031L72.7051 307.592C73.1157 307.44 73.4399 307.116 73.5918 306.705L78.0312 294.708Z'
          fill='#C4C2BB'
          stroke='#8A8A8A'
        />
      </motion.g>
    </svg>
  )
}

export default HeroGrid
